export { default as Features } from './Features';
export { default as Folio } from './Folio';
export { default as Gallery } from './Gallery';
export { default as Hero } from './Hero';
export { default as Services } from './Services';
export { default as HowItWorks} from './HowItWorks';
export { default as Sponsors } from './Sponsors';
export { default as Topbar } from './layouts/Navigation/Topbar/Topbar';
export { default as Faq } from './layouts/Faq';
export {default as SuccessDefault} from '../success';
export {default as AboutDefault} from '../about';
